version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always

    environment:
      POSTGRES_DB: anyDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./databaseSchema:/docker-entrypoint-initdb.d  #init
    ports:
      - "5432:5432"
